apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: openmrs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: openmrs
  template:
    metadata:
      labels:
        app: openmrs
        version: "1.0"
    spec:
      containers:
        - name: openmrs
          image: shashikamle.jfrog.io/openmrs/openmrs:2.0
          ports:
            - containerPort: 8080
              protocol: TCP
